name: Build page
on: 
  workflow_dispatch:
  repository_dispatch:
    types: trigger_build
concurrency:
  group: cms2web
permissions:
  contents: write
env:
  BUILD_PATH: ${{ github.event.client_payload.build_path }}
  TEMPLATE: ${{ github.event.client_payload.template }}
  FETCH_URL: ${{ github.event.client_payload.fetch_url }}
  LOG_URL: ${{ github.event.client_payload.log_url }}
  APEX_SESSION: ${{ github.event.client_payload.apex_session }}
  SITE_ID: ${{ github.event.client_payload.site_id }}
jobs:
  build_page:
    name: Build page
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      # Print environment variales passed from Oracle CMS
      - run: |
          echo "BUILD_PATH:${BUILD_PATH}"
          echo "TEMPLATE:${TEMPLATE}"
          echo "FETCH_URL:${FETCH_URL}"
          echo "LOG_URL:${LOG_URL}"
          echo "APEX_SESSION:${APEX_SESSION}"
          echo "SITE_ID:${SITE_ID}"
          
      # Log status
      - run: curl -X POST ${LOG_URL} -H "Apex-Session:${APEX_SESSION}" -H 'Content-Type:application/json' -d "{\"site_id\":\"${SITE_ID}\",\"status\":\"Github action started\",\"exitcode\":0}" 
      # Get latest updates
      - uses: actions/checkout@v3

      # Install node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install node_modules
      - run: npm install

      #  Transpile typescript
      - run: |
          set +e
          npx tsc ./TEMPLATES/$TEMPLATE/index.ts --outFile ./TEMPLATES/$TEMPLATE/index.js
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          curl -X POST ${LOG_URL} -H "Apex-Session:${APEX_SESSION}" -H 'Content-Type:application/json' -d "{\"site_id\":\"${SITE_ID}\",\"status\":\"Transpile Typescript\",\"exitcode\":${exitcode}}"
          exit "$exitcode"

      #  Remove any existing BUILD_PATH directory and its contents
      - run: |
          set +e
          rm -rvf ./${BUILD_PATH}
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          curl -X POST ${LOG_URL} -H "Apex-Session:${APEX_SESSION}" -H 'Content-Type:application/json' -d "{\"site_id\":\"${SITE_ID}\",\"status\":\"Clean target directory\",\"exitcode\":${exitcode}}"
          exit "$exitcode"
      
      #  Build with Eleventy
      - run: |
          set +e
          npx @11ty/eleventy
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          curl -X POST ${LOG_URL} -H "Apex-Session:${APEX_SESSION}" -H 'Content-Type:application/json' -d "{\"site_id\":\"${SITE_ID}\",\"status\":\"Eleventy build pages\",\"exitcode\":${exitcode}}"
          exit "$exitcode"
          
      # Git push build
      - run: |
          set +e
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./$BUILD_PATH
          git commit -m build
          git push
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          curl -X POST ${LOG_URL} -H "Apex-Session:${APEX_SESSION}" -H 'Content-Type:application/json' -d "{\"site_id\":\"${SITE_ID}\",\"status\":\"Github action completed\",\"exitcode\":${exitcode}}"
          exit "$exitcode"
