name: Build page
on: 
  workflow_dispatch:
  repository_dispatch:
    types: trigger_build
permissions:
  contents: write
env:
  BUILD_PATH: ${{ github.event.client_payload.build_path }}
  TEMPLATE: ${{ github.event.client_payload.template }}
  FETCH_URL: ${{ github.event.client_payload.fetch_url }}
  LOG_URL: ${{ github.event.client_payload.log_url }}
jobs:
  build_page:
    name: Build page
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      # Log status
      - run: curl -X POST ${LOG_URL} -H 'Content-Type:application/json' -d '{"status":"Github action started"}'
      
      # Get latest updates repo
      - uses: actions/checkout@v3

      # Install node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install node_modules
      - run: npm install

      #  Transpile typescript
      - run: |
          set +e
          npx tsc ./TEMPLATES/$TEMPLATE/index.ts --outFile ./TEMPLATES/$TEMPLATE/index.js
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          curl -X POST ${LOG_URL}?${exitcode} -H 'Content-Type:application/json' -d '{"status":"Transpile Typescript"}'
          exit "$exitcode"

      #  Remove any existing BUILD_PATH directory and its contents
      - run: rm -v ./${BUILD_PATH}/*
      
      #  Build with Eleventy
      - run: |
          set +e
          npx @11ty/eleventy
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          curl -X POST ${LOG_URL}?${exitcode} -H 'Content-Type:application/json' -d '{"status":"Eleventy build pages"}'
          exit "$exitcode"
          
      # Git push build
      - run: |
          set +e
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./$BUILD_PATH
          git commit -m build
          git push
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          curl -X POST ${LOG_URL}?${exitcode} -H 'Content-Type:application/json' -d '{"status":"Github action completed"}'
          exit "$exitcode"
